name: robustremedy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.0.0+54

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  vector_math: any
  flutter_swiper: 1.1.6
  flutter_svg: ^0.19.1
  localstorage: ^3.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  google_fonts:
  sweetalert: any
  badges: ^1.1.6
  connectivity: ^0.4.8+2
  toast:
  flutter_icons:
  shared_preferences:
  flutter_session:
  flutter_form_builder:
  geolocator: '^5.1.1'
  geocoder: ^0.2.1
  flutter_open_whatsapp:
  font_awesome_flutter:
  double_back_to_close_app:
  flutter_html:
  material_floating_search_bar: ^0.2.6
  file_picker: ^1.9.0+1
  dio: ^3.0.9
  path:
  translator:
  filter_list:
  modal_bottom_sheet:
  flutter_local_notifications:
  timeline_node:
  get_it:
  url_launcher:
  expansion_card:
  flutter_rating_bar:
  share:
  flutter_range_slider:
  showcaseview:
  bouncing_widget:
  flutter_phone_direct_caller:
  webview_flutter:
  flutter_typeahead: ^2.0.0
  image_picker: ^0.6.7+22
  change_app_package_name: ^1.0.0
  dropdown_search:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/Appicon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/Drawer/
    - assets/Login/
    - assets/icons/
    - assets/intro/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
